Movies/Controllers/ActorMovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Movies.Controllers
{
    public class ActorMovieController : Controller
    {
        private readonly ModelContainer db = new ModelContainer();

        ~ActorMovieController()
        {
            if (db != null)
            {
                db.Dispose();
            }
        }
        // GET: ActorMovie
        public ActionResult Create(int? movieId,int? actorId)
        {
            if (movieId==null || actorId==null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(movieId);
            Person person = db.People.Find(actorId);
            movie.People.Add(person);
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.AbsolutePath);
        }
        public ActionResult Delete(int? movieId, int? actorId)
        {
            if (movieId == null || actorId == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(movieId);
            Person person = db.People.Find(actorId);
            movie.People.Remove(person);
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.AbsolutePath);
        }
    }
}

Movies/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Movies.Controllers
{
    public class ActorsController : Controller
    {
        private readonly ModelContainer db = new ModelContainer();

        ~ActorsController()
        {
            if (db != null)
            {
                db.Dispose();
            }
        }

        // GET: Actors
        public ActionResult Index()
        {
            return View(db.People);
        }

        // GET: Actors/Details/5
        public ActionResult Details(int? id)
        {
            if (id==null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            else
            {
                var actor = db.People.Find(id);
                if (actor==null)
                {
                    return new HttpNotFoundResult();
                }
                return View(actor);
            }
        }

        // GET: Actors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        [HttpPost]
        public ActionResult Create([Bind(Include ="Firstname, Lastname")]Person person)
        {
            if (ModelState.IsValid)
            {
                Person actor = db.People.Add(person);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        // GET: Actors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id==null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest); 
            }
            Person actor = db.People.Find(id);
            if (actor==null)
            {
                return new HttpNotFoundResult();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            Person personToUpdate = db.People.Find(id);
            if (TryUpdateModel(personToUpdate,"",new string[] { "Firstname","Lastname"}))
            {
                db.Entry(personToUpdate).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(personToUpdate);
        }

        // GET: Actors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Person actor = db.People.Find(id);
            if (actor == null)
            {
                return new HttpNotFoundResult();
            }
            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            db.Movies.ToList().Where(movie => movie.People.ToList().Where(p => p.IDPerson == id) != null).ToList().ForEach(movie =>
            {
                db.People.Find(id).Movies.Remove(movie);
            });

            db.People.Remove(db.People.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Movies/Controllers/FilesController.cs
using System.Web.Mvc;

namespace Movies.Controllers
{
    public class FilesController : Controller
    {
        private readonly ModelContainer db = new ModelContainer();
        ~FilesController()
        {
            if (db != null)
            {
                db.Dispose();
            }
        }

        // GET: Files
        public ActionResult Index(int id)
        {
            var uploadedPoster=db.UploadedPosters.Find(id);
            return File(uploadedPoster.Content,uploadedPoster.ContentType);
        }

        // DELETE
        public ActionResult Delete(int id)
        {
            db.UploadedPosters.Remove(db.UploadedPosters.Find(id));
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.AbsolutePath);
        }
    }
}

Movies/Controllers/MoviesController.cs
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using Movies.Models;
using System;
using System.Collections.Generic;
using System.Web;

namespace Movies.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ModelContainer db=new ModelContainer();

        ~MoviesController(){
            if (db!=null)
            {
                db.Dispose();
            }
        }

        // GET: Movies
        public ActionResult Index()
        {
            return View(db.Movies);
        }

        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id==null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies
                .Include(m=>m.UploadedPosters)
                .SingleOrDefault(m=>m.IDMovie==id);
            if (movie==null)
            {
                return new HttpNotFoundResult();
            }
            return View(movie);
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            ViewBag.genres = Enum.GetValues(typeof(Genre));
            return View();
        }

        // POST: Movies/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "Title, Genre, Duration")]Movie movie,IEnumerable<HttpPostedFileBase> files)
        {
            if (ModelState.IsValid)
            {
                movie.UploadedPosters = new List<UploadedPosters>();
                foreach (var file in files)
                {
                    if (file!=null && file.ContentLength>0)
                    {
                        var poster = new UploadedPosters
                        {
                            Name = System.IO.Path.GetFileName(file.FileName),
                            ContentType = file.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(file.InputStream))
                        {
                            poster.Content = reader.ReadBytes(file.ContentLength);
                        }
                        movie.UploadedPosters.Add(poster);
                    }
                }

                db.Movies.Add(movie);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.genres = Enum.GetValues(typeof(Genre));
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies
                .Include(m => m.UploadedPosters)
                .SingleOrDefault(m => m.IDMovie == id);
            if (movie == null)
            {
                return new HttpNotFoundResult();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditConfirmed(int id, FormCollection collection,IEnumerable<HttpPostedFileBase> files)
        {
            Movie movieToUpdate = db.Movies.Find(id);
            if (TryUpdateModel(movieToUpdate,"",new string[] { "Title","Genre","Duration"}))
            {
                if (movieToUpdate.UploadedPosters!=null)
                {
                    foreach (var file in files)
                    {
                        if (file != null && file.ContentLength > 0)
                        {
                            var poster = new UploadedPosters
                            {
                                Name = System.IO.Path.GetFileName(file.FileName),
                                ContentType = file.ContentType
                            };
                            using (var reader = new System.IO.BinaryReader(file.InputStream))
                            {
                                poster.Content = reader.ReadBytes(file.ContentLength);
                            }
                            movieToUpdate.UploadedPosters.Add(poster);
                        }
                    }
                }

                db.Entry(movieToUpdate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movieToUpdate);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies
                .Include(m => m.UploadedPosters)
                .SingleOrDefault(m => m.IDMovie == id);
            if (movie == null)
            {
                return new HttpNotFoundResult();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            db.UploadedPosters.RemoveRange(db.UploadedPosters.Where(m => m.MovieIDMovie == id));
            db.Movies.Remove(db.Movies.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Actors(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies
                .SingleOrDefault(m => m.IDMovie == id);
            if (movie == null)
            {
                return new HttpNotFoundResult();
            }
            List<Person> people = new List<Person>();
            
            foreach (var item in db.People)
            {
                if (!movie.People.Contains(item))
                {
                    people.Add(item);
                }
            }
            var other = db.People.ToList().Where(p => !movie.People.Contains(p)).ToList();
            ViewBag.otherActors = other ?? new List<Person>();
            TempData["movieID"] = id;
            TempData.Keep("movieID");
            return View(movie.People);
        }

        [HttpPost]
        [ActionName("Actors")]
        public ActionResult ActorsConfirmed([Bind(Include = "IDPerson")] Person person)
        {
            int? movieId = (int)TempData["movieID"];
            if (movieId == null || person?.IDPerson == 0)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(movieId);
            Person person_ = db.People.Find(person.IDPerson);
            movie.People.Add(person_);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Movies/Views/Movies/Actors.cshtml
@model IEnumerable<Movies.Person>

@{
    ViewBag.Title = "Actors";
    var ddlActors = new SelectList(items: ViewBag.otherActors, dataTextField: "FullName", dataValueField: "IDPerson");
    var movieID = TempData["movieID"];
}

<h2>Actors</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.Label("Add actor:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList(name: "IDPerson", selectList: ddlActors, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div style="margin-top:10px;margin-bottom:10px" class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Actor" title="Add" formmethod="post" class="btn btn-primary" />
        </div>
    </div>
}

@using (Html.BeginForm())
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IDPerson)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Firstname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lastname)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IDPerson)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Firstname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lastname)
                </td>
                <td>
                    @Ajax.ActionLink("Delete actor", "Delete", "ActorMovie",
                              new { actorId = item.IDPerson, movieID = movieID }, new AjaxOptions { HttpMethod = "Get" })
                </td>
            </tr>
        }


    </table>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Movies/Views/Movies/Create.cshtml
@model Movies.Movie

@{
    ViewBag.Title = "Create";
    var ddlGenre = new SelectList(items: ViewBag.Genres);
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Movies",null,FormMethod.Post,new { enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Movie</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList(name: "Genre", selectList: ddlGenre, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", min = 50, max = 200 } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Picture", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="Picture" multiple accept="image/*" name="files" />
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Movies/Views/Movies/Delete.cshtml
@model Movies.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        @Html.HiddenFor(model => model.IDMovie)

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        @foreach (var uploadedPoster in Model.UploadedPosters)
        {
            <dt>
                @uploadedPoster.Name
            </dt>

            <dd style="margin-top:10px">
                <img src="~/Files?id=@uploadedPoster.IDUploadedPoster" alt="picture" width="300" height="200" />
            </dd>
        }
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Movies/Views/Movies/Details.cshtml
@model Movies.Movie

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">

        @Html.HiddenFor(model => model.IDMovie)

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        @foreach (var uploadedPoster in Model.UploadedPosters)
        {
            <dt>
                @uploadedPoster.Name
            </dt>

            <dd style="margin-top:10px">
                <img src="~/Files?id=@uploadedPoster.IDUploadedPoster" alt="picture" width="300" height="200" />
            </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDMovie }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Movies/Views/Movies/Edit.cshtml
@model Movies.Movie

@{
    ViewBag.Title = "Edit";
    var ddlGenre = new SelectList(items: ViewBag.Genres);
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Movies", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Movie</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IDMovie)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList(name: "Genre", selectList: ddlGenre, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Picture", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="Picture" multiple accept="image/*" name="files" />
        </div>
    </div>

    @foreach (var uploadedPoster in Model.UploadedPosters)
    {
        <div class="form-group">
            <span class="control-label col-md-2">
                <stron>@uploadedPoster.Name</stron>
                @Ajax.ActionLink("Delete", "Delete", "Files",
                        new { id = uploadedPoster.IDUploadedPoster }, new AjaxOptions { HttpMethod = "Post" })
            </span>
            <div class="col-md-10">
                <img src="~/Files?id=@uploadedPoster.IDUploadedPoster" alt="picture" width="300" height="200" />
            </div>
        </div>
    }

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Movies/Views/Movies/Index.cshtml
@model IEnumerable<Movies.Movie>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDMovie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IDMovie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Duration)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.IDMovie }) |
            @Html.ActionLink("Details", "Details", new { id = item.IDMovie }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.IDMovie }) |
            @Html.ActionLink("Actors", "Actors", new { id = item.IDMovie }) 
        </td>
    </tr>
}

</table>